/**
 * Created by mupxq on 8/28/17.
 */
export const TODOLIST_REMOVE = 'TODOLIST_REMOVE';
export const TODOLIST_UPDATE = 'TODOLIST_UPDATE';
export const SINGLETODOLIST_UPDATE = 'SINGLETODOLIST_UPDATE';
export const TODOLIST_ADD = 'TODOLIST_ADD';